Changed build workflow
Changed the build workflow because of the following error:

 Current runner version: '2.335.1'
Runner Image Provisioner
Operating System
Runner Image
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action powershell/powershell-for-github-actions, repository not found

Removed the powershell setup part because it is not necessary.