Changed testing workflow on linux
The linux testing workflow got an error:

Current runner version: '2.335.1'
Runner Image Provisioner
Operating System
Runner Image
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `powershell/powershell@v2`, unable to find version `v2`

This will be fixed in the new version.